spring:
  application:
    name: generic-backend
  profiles:
    active: "local"

#  server:
#    context-path: /simple-war/api
#    port: 8080

info:
  app:
    name: Generic Backend Application
    description:
    version: 1.0.0

---

spring:
  profiles: local

application:
  mongo:
    host: localhost
    port: 27017
    databaseName: genericBackendDb

---

spring:
  profiles: dev

---

spring:
  profiles: qa

---

spring:
  profiles: prod

